### ISSUE TITLE
Plugin installation failed using the Framework

### ISSUE THREAD

**Issue by shonesque** [deltanet/adapt-nav-link#20]
I have tried to run the install using the Adapt-cli and the package seems not to be working.

There is no clear documentation over hot to install it using the framework.

Please advise.

**Comment by RobertPeek** [comment]
@shonesque the plugin isn't yet registered so unfortunately it needs to be installed manually. To do this just download the latest release and copy the folder into your frameworks 'src/extensions' folder.

The plugin can then be configured as required by using the example.json file.

Hope that helps!

**Comment by shonesque** [comment]
Thanks man
